main: com.projectcitybuild.PCBridge
name: PCBridge
version: 1.0.0

commands:
   announce:
      description: Announces a message to the server
      usage: /announce <message>
   maintenance:
      description: Toggles 'Maintenance Mode' on the server, allowing only staff to connect
      usage: /maintenance [on|off] [message]