name: PCBridge
main: com.pcb.pcbridge.PCBridge
version: 2.1.0
website: https://projectcitybuild.com
description: Bridges PCB game servers with the website
depend: [Essentials]

commands:
  ban:
  unban:
  mute: