name: PCBridge
main: com.pcb.pcbridge.PCBridge
version: 3.0.0
website: https://projectcitybuild.com
description: Bridges PCB game servers with the website
depend: [Essentials]

commands:
  maintenance:
    description: De/activates service maintenance mode
    usage: "/maintenance [on|off]"
    permission: pcbridge.maintenance.set